{% set name = "lal" %}
{% set version = "7.1.2" %}
{% set sha256 = "f777ce770215786a0c810ce362cdeea6d7256090bc9963df244a69375b25e9a6" %}

# define build number
{% set build = 0 %}

# default FFT implememntation to FFTW
{% set fft_impl = fft_impl or 'fftw' %}

# prefer FFTW builds over MKL using a build number offset
{% if fft_impl == 'fftw' %}
{% set build = build + 100 %}
{% endif %}

# dependency versions
{% set swig_version = "3.0.10" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/lalsuite/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  ignore_run_exports:
    - blas
    # run_exports parsing for fftw is broken, so we ignore it
    # manually, for now
    - fftw
  number: {{ build }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config >=0.18.0
    - make
    - help2man >=1.37
    - bc
    - swig >={{ swig_version }}
  host:
    - fftw * nompi*  # [fft_impl == "fftw"]
    - gsl
    - hdf5
    - mkl-devel {{ mkl }}  # [fft_impl == "mkl"]
    - zlib

outputs:
  - name: liblal
    script: install-lib.sh
    build:
      run_exports:
        - {{ pin_subpackage("liblal", max_pin="x") }}
      string: {{ fft_impl }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
    requirements:
      build:
        - {{ compiler('c') }}
        - make  # [not win]
        - swig >=3.0.9
      host:
        - fftw * nompi*  # [fft_impl == "fftw"]
        - gsl
        - hdf5
        - mkl-devel {{ mkl }}  # [fft_impl == "mkl"]
        - zlib
      run:
        - fftw  # [fft_impl == "fftw"]
        - gsl
        - hdf5
        - zlib
      run_constrained:
        # 7.1.1 is the version where the packages were restructured
        - lal >=7.1.1
        - python-lal >=7.1.1

    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lal/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Library shared object libraries
      description: |
        The LSC Algorithm Library for gravitational wave data analysis.
        This package contains the shared object libraries need to build
        applications that use LAL.
    test:
      requires:
        - pkg-config
      commands:
        - test $(pkg-config --modversion --print-errors lal) == "${PKG_VERSION}"
        - test $(pkg-config --modversion --print-errors lalsupport) == "${PKG_VERSION}"

  - name: python-lal
    script: install-python.sh
    build:
      ignore_run_exports:
        - mkl
        # ignore run_exports from python's recipe
        - python
      string: {{ fft_impl }}_py{{ py }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
    requirements:
      build:
        - {{ compiler('c') }}
        - make
        - pkg-config >=0.18.0
        - swig >={{ swig_version }}
      host:
        - {{ pin_subpackage('liblal', exact=True) }}
        - mkl-devel {{ mkl }}  # [fft_impl == "mkl"]
        - numpy
        - python
      run:
        # NOTE: on linux, python-lal links the LAL dependencies
        #       as well so we have to list them here. why this
        #       doesn't happen on osx, I'm not sure.
        - {{ pin_subpackage('liblal', exact=True) }}
        - ligo-segments
        - lscsoft-glue >=1.54.1
        - {{ pin_compatible('numpy') }}
        # swig bindings cause segmentation fault
        - numpy <1.20.0a0
        - python
        - python-dateutil
        - python-ligo-lw
        - scipy
        - six
    test:
      requires:
        - freezegun
        - pytest >=4.0.0a0
      source_files:
        - test/python
      commands:
        - python -m pytest -rs -v test/python
      imports:
        - lal
        - lal.antenna
        - lal.gpstime
        - lal.rate
        - lal.series
        - lal.utils
    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lal/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Library Python bindings
      description: |
        The LSC Algorithm Library for gravitational wave data analysis.
        This package contains the Python bindings.

  - name: lal
    script: install-bin.sh
    build:
      ignore_run_exports:
        - python
      string: {{ fft_impl }}_py{{ py }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
    requirements:
      build:
        - {{ compiler('c') }}
        - make
      host:
        - {{ pin_subpackage('liblal', exact=True) }}
        # this is here in case the solver gets confused during conda-build
        - mkl {{ mkl }}  # [fft_impl == "mkl"]
        - python
      run:
        - {{ pin_subpackage('liblal', exact=True) }}
        - python
        - {{ pin_subpackage('python-lal', exact=True) }}
    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lal/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Library runtime tools
      description: |
        The LSC Algorithm Library for gravitational wave data analysis.
        This package contains the runtime tools.
    test:
      commands:
        - lal_version --verbose
        - lal_simd_detect
      imports:
        - lal

about:
  home: https://wiki.ligo.org/Computing/LALSuite
  doc_url: https://lscsoft.docs.ligo.org/lalsuite/lal/
  dev_url: https://git.ligo.org/lscsoft/lalsuite/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: LSC Algorithm Library
  description: |
    The LSC Algorithm Library for gravitational wave data analysis.
    This package contains the shared-object libraries needed to run
    applications that use the LAL library.  If you want to install
    the Python bindings, please install the associated python-lal
    package.

extra:
  feedstock-name: lal
  recipe-maintainers:
    - duncanmmacleod
    - skymoo
