{% set name = "lal" %}
{% set version = "6.19.0" %}
{% set sha256 = "729934a2f403b13f9c4f98d4d5e5d7fa4ea4e1158994165b42acc7e8149b4509" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: http://software.ligo.org/lscsoft/source/lalsuite/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 1001
  skip: true  # [win]

outputs:
  - name: lal
    script: install-c.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - make
        - pkg-config
      host:
        - swig >=3.0.7
        - mkl-devel  {{ mkl }}  # [blas_impl == "mkl"]
        - openblas-devel {{ openblas }}  # [blas_impl == "openblas"]
        - gsl
        - zlib
        - fftw
        - hdf5
      run:
        - gsl
        - zlib
        - fftw
        - hdf5
    test:
      commands:
        - lal_version --verbose
        - lal_simd_detect
    about:
      home: https://wiki.ligo.org/DASWG/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lal/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPLv3
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Library
      description: |
        The LSC Algorithm Library for gravitational wave data analysis.
        This package contains the shared-object libraries and python bindings
        needed to run applications that use the LAL library.
  - name: python-lal
    script: install-python.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - make
        - pkg-config
      host:
        - swig >=3.0.7
        - {{ pin_subpackage('lal', exact=True) }}
        - python
        - numpy
        - six
        - ligo-segments
        - lscsoft-glue
        - scipy
      run:
        - {{ pin_subpackage('lal', exact=True) }}
        - python
        - {{ pin_compatible('numpy') }}
        - six
        - python-dateutil
        - ligo-segments
        - lscsoft-glue
        - scipy
    test:
      imports:
        - lal
        - lal.gpstime
        - lal.rate
        - lal.series
        - lal.utils
    about:
      home: https://wiki.ligo.org/DASWG/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lal/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPLv3
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Library
      description: |
        The LSC Algorithm Library for gravitational wave data analysis.
        This package contains the Python bindings.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - skymoo
