{% set name = "lal" %}
{% set version = "6.19.2" %}
{% set sha256 = "2f9035561093651f1f5dc29b20701df14497f4e493c7e26a74e3cd5c1b51baad" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: http://software.ligo.org/lscsoft/source/lalsuite/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - make
    - bc
    - swig >=3.0.7
  host:
    - gsl
    - zlib
    - fftw
    - hdf5
  run:
    - gsl
    - zlib
    - fftw
    - hdf5

test:
  commands:
    - lal_version --verbose
    - lal_simd_detect

outputs:
  - name: lal
    build:
      run_exports:
        - {{ pin_subpackage("lal", max_pin="x.x") }}

  - name: python-lal
    script: install-python.sh
    build:
      activate_in_script: True
    requirements:
      build:
        - {{ compiler('c') }}
        - make
        - pkg-config
        - swig >=3.0.7
      host:
        - {{ pin_subpackage('lal', exact=True) }}
        - python
        - numpy
        - six
        - ligo-segments
        - lscsoft-glue
        - scipy
        - gsl
      run:
        - {{ pin_subpackage('lal', exact=True) }}
        - python
        - {{ pin_compatible('numpy') }}
        - six
        - python-dateutil
        - ligo-segments
        - lscsoft-glue
        - scipy
        - gsl
    test:
      imports:
        - lal
        - lal.antenna
        - lal.gpstime
        - lal.rate
        - lal.series
        - lal.utils
    about:
      home: https://wiki.ligo.org/DASWG/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lal/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPLv3
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Library
      description: |
        The LSC Algorithm Library for gravitational wave data analysis.
        This package contains the Python bindings.

about:
  home: https://wiki.ligo.org/DASWG/LALSuite
  doc_url: https://lscsoft.docs.ligo.org/lalsuite/lal/
  dev_url: https://git.ligo.org/lscsoft/lalsuite/
  license: GPLv3
  license_family: GPL
  license_file: COPYING
  summary: LSC Algorithm Library
  description: |
    The LSC Algorithm Library for gravitational wave data analysis.
    This package contains the shared-object libraries needed to run
    applications that use the LAL library.  If you want to install
    the Python bindings, please install the associated python-lal
    package.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - skymoo
