{% set name = "lal" %}
{% set version = "6.18.0" %}
{% set sha256 = "464601c529f5607c251a54843e749bc9bd962055cc04ba21fdf6150e392a0ba2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: http://software.ligo.org/lscsoft/source/lalsuite/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 3
  skip: true  # [win]

requirements:
  build:
    - pkg-config
    - make
    - {{ compiler('c') }}
    - bc
    - swig>=3.0.7
  host:
    - blas 1.1 openblas
    - openblas
    - gsl
    - zlib
    - fftw
    - hdf5
    - python
    - numpy
    - six
    - lscsoft-glue

test:
  imports:
    - lal
  commands:
    - lal_version --help

outputs:
  - name: lal
    requirements:
      build:
        - {{ compiler('c') }}
      host:
        - blas 1.1 openblas
        - openblas
        - gsl
        - zlib
        - fftw
        - hdf5
      run:
        - blas 1.1 openblas
        - openblas
        - gsl
        - zlib
        - fftw
        - hdf5
    files:
      - bin/lal_version
      - bin/lal_simd_detect
      - etc/lal-user-env.*
      - include/lal/
      - lib/liblal*
      - lib/pkgconfig/lal*.pc
    test:
      commands:
        - lal_version --verbose
        - lal_simd_detect
    about:
      home: https://wiki.ligo.org/DASWG/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lal/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPLv3
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Library
      description: |
        The LSC Algorithm Library for gravitational wave data analysis.
        This package contains the shared-object libraries and python bindings
        needed to run applications that use the LAL library.
  - name: python-lal
    requirements:
      build:
        - {{ compiler('c') }}
        - swig>=3.0.7
      host:
        - {{ pin_subpackage('lal', exact=True) }}
        - python
        - numpy
      run:
        - {{ pin_subpackage('lal', exact=True) }}
        - python
        - numpy
        - six
        - lscsoft-glue
    files:
      - lib/python*/site-packages/lal/**
    test:
      imports:
        - lal
        - lal.utils
    about:
      home: https://wiki.ligo.org/DASWG/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lal/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPLv3
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Library
      description: |
        The LSC Algorithm Library for gravitational wave data analysis.
        This package contains the Python bindings.

about:
  home: https://wiki.ligo.org/DASWG/LALSuite
  license: GPLv3
  license_family: GPL
  summary: LSC Algorithm Library

extra:
  recipe-maintainers:
    - duncanmmacleod
    - skymoo
