travis:
  secure:
    BINSTAR_TOKEN: rmLQtl1yucasYkFwEeAfML7L0MKh1hFHXFYQvIBVWIObqx3KYNzrADneIzyolpcL82TQ2BBLUloeJV9vsz6VHn2Ln6Q9JpnPiEs6BCwSgezErxk6N1R4ulx5+ySwJ0fiKjUyeBshTiQCp1RKo5fxUPj53Nqe/BmT+5XZoJpdNnmqoJLNysbTpGDha5vwS+t5GqnBM89Z0uHJuzMWe/Y2KEbH7UMz1h9di+OGBYcpq4TqzIBpnRGIxYYUoAUIj3tTIhIkrjITPOL/w+734B2K2Ef9Tn8sVifbbpBu4GDVsl2qIetPT5Hn0YGGLBTw8TxMqu/lIGK5xjpKWFaYahg/wGH0oZQllSYlcaMHQ7wWoStIyJYyotMOexiL+pY/XU3SCZqeUhHaE9KEOkx+Is3s/RY5pjT4EaCHT/J3olzXqDt6WOcLznEjyzeA2scjKpMot9FwlUKB9xWdRypsL1LX1ptD3J67+nTOsItRSDUz4Jki7KhQb2Fkzj/zcwHxA0fDvMT1zhGcOKVB9y6JmNE34ueh6Pxghswldj7++E3p3S6XAat+dAxaPPTkOanL8X4BnkTtJcLsr+jS2eQ7mq8tdGsj7f5yD1fTORgCZhabRd5k87SDdMqV57VeyS0wrr7RZFR6fOpsp6twKuiBDNMW4w7cft4J5eEPJ7WpPPl5jdI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
